# # =============== stanford =======================
# dataset: stanford          # select one
# labels:
#   - SOH
# # =============== stanford =======================

# =============== nasa =======================
dataset: nasa
labels:
  - capacity
# =============== nasa =======================

features:
  - voltage       # Voltage feature
  - current  
  - temperature
  - relativeTime

data_groupby:
  - cycle

sequence_length: 50

n_trials: 30

 